name: my first workflow

on: push

jobs:
    first-job:
         runs-on: ubuntu-latest
         steps:
             - name: checkout 
               uses: actions/checkout@v4
               
             - name: welcome message
               run: echo "my first github actions task"
             
             - name: list files
               run: ls
            
             - name: read file
               run: cat README.md
            