name: using secret and varibles 

on: push

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - name: calling environment variable
          run: echo "name=${{ .vars.NAME}}"
         
        - name: call secret 
          run: echo "my company name is ${{ .secrets.COMPANY }}